export default {
  login: 'MARConthemove',
  id: 62877154,
  node_id: 'MDQ6VXNlcjYyODc3MTU0',
  avatar_url: 'https://avatars.githubusercontent.com/u/62877154?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/MARConthemove',
  html_url: 'https://github.com/MARConthemove',
  followers_url: 'https://api.github.com/users/MARConthemove/followers',
  following_url:
    'https://api.github.com/users/MARConthemove/following{/other_user}',
  gists_url: 'https://api.github.com/users/MARConthemove/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/MARConthemove/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/MARConthemove/subscriptions',
  organizations_url: 'https://api.github.com/users/MARConthemove/orgs',
  repos_url: 'https://api.github.com/users/MARConthemove/repos',
  events_url: 'https://api.github.com/users/MARConthemove/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/MARConthemove/received_events',
  type: 'User',
  site_admin: false,
  name: 'Marc - Fabian Gätcke',
  company: 'justAnotherCoder',
  blog: 'www.MARConthemove.com',
  location: 'Berlin, Germany',
  email: null,
  hireable: null,
  bio: 'Creator of justAnotherCoder',
  twitter_username: 'marc_onthemove',
  public_repos: 29,
  public_gists: 9,
  followers: 5,
  following: 12,
  created_at: '2020-03-30T08:46:35Z',
  updated_at: '2022-07-18T07:03:50Z',
}
